// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atvogmnnaenixgjngnpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0dm9nbW5uYWVuaXhnam5nbnBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3Mzc4MzYsImV4cCI6MjA2ODMxMzgzNn0.AUGPNFEs7Iz6Wn6mn0Yu0uTfM25MRv3fLhwblHei8e0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});